version: '3'

vars:
  PYTHON: python3
  VENV_DIR: .venv
  BACKEND_DIR: backend
  FRONTEND_DIR: frontend
  BACKEND_PORT: 8000
  FRONTEND_PORT: 5173

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Setup tasks
  setup:
    desc: Complete setup for local development (backend + frontend)
    cmds:
      - task: setup-backend
      - task: setup-frontend

  setup-backend:
    desc: Set up Python virtual environment and install backend dependencies
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - "{{.PYTHON}} -m venv ../{{.VENV_DIR}}"
      - "../{{.VENV_DIR}}/bin/pip install --upgrade pip"
      - "../{{.VENV_DIR}}/bin/pip install -e ."
      - echo "Backend setup complete. Virtual environment created at {{.VENV_DIR}}"
    status:
      - test -d ../{{.VENV_DIR}}

  setup-frontend:
    desc: Install frontend dependencies
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm install
      - echo "Frontend setup complete"
    status:
      - test -d node_modules

  # Run tasks
  dev:
    desc: Run both backend and frontend in development mode
    deps: [setup]
    cmds:
      - echo "Note - Run task backend and task frontend in separate terminals"

  backend:
    desc: Run backend development server
    dir: "{{.BACKEND_DIR}}"
    deps: [setup-backend]
    cmds:
      - echo "Starting backend on http://localhost:{{.BACKEND_PORT}}"
      - "../{{.VENV_DIR}}/bin/uvicorn app.main:app --reload --host 0.0.0.0 --port {{.BACKEND_PORT}}"

  frontend:
    desc: Run frontend development server
    dir: "{{.FRONTEND_DIR}}"
    deps: [setup-frontend]
    cmds:
      - echo "Starting frontend on http://localhost:{{.FRONTEND_PORT}}"
      - npm run dev

  # Background process management
  start-bg:
    desc: Start both backend and frontend in background
    deps: [setup]
    cmds:
      - task: backend-bg
      - task: frontend-bg
      - sleep 2
      - task: status-bg

  backend-bg:
    desc: Start backend in background
    deps: [setup-backend]
    cmds:
      - bash scripts/start-backend.sh

  frontend-bg:
    desc: Start frontend in background
    deps: [setup-frontend]
    cmds:
      - bash scripts/start-frontend.sh

  stop-bg:
    desc: Stop background processes
    cmds:
      - |
        if [ -f .pids/backend.pid ]; then
          PID=$(cat .pids/backend.pid)
          if kill -0 $PID 2>/dev/null; then
            kill $PID
            echo "Backend stopped (PID: $PID)"
          fi
          rm -f .pids/backend.pid
        else
          echo "Backend not running"
        fi
      - |
        if [ -f .pids/frontend.pid ]; then
          PID=$(cat .pids/frontend.pid)
          if kill -0 $PID 2>/dev/null; then
            kill $PID
            echo "Frontend stopped (PID: $PID)"
          fi
          rm -f .pids/frontend.pid
        else
          echo "Frontend not running"
        fi

  restart-bg:
    desc: Restart background processes
    cmds:
      - task: stop-bg
      - sleep 1
      - task: start-bg

  status-bg:
    desc: Show status of background processes
    cmds:
      - |
        echo "Process Status:"
        echo ""
        if [ -f .pids/backend.pid ]; then
          PID=$(cat .pids/backend.pid)
          if kill -0 $PID 2>/dev/null; then
            echo "✓ Backend  - Running (PID: $PID) - http://localhost:{{.BACKEND_PORT}}"
          else
            echo "✗ Backend  - Not running (stale PID file)"
            rm -f .pids/backend.pid
          fi
        else
          echo "✗ Backend  - Not running"
        fi
        
        if [ -f .pids/frontend.pid ]; then
          PID=$(cat .pids/frontend.pid)
          if kill -0 $PID 2>/dev/null; then
            echo "✓ Frontend - Running (PID: $PID) - http://localhost:{{.FRONTEND_PORT}}"
          else
            echo "✗ Frontend - Not running (stale PID file)"
            rm -f .pids/frontend.pid
          fi
        else
          echo "✗ Frontend - Not running"
        fi

  logs-backend:
    desc: Tail backend logs
    cmds:
      - tail -f logs/backend.log

  logs-frontend:
    desc: Tail frontend logs
    cmds:
      - tail -f logs/frontend.log

  logs:
    desc: Tail all logs
    cmds:
      - tail -f logs/backend.log logs/frontend.log

  # Database tasks
  db-init:
    desc: Initialize the main database
    dir: "{{.BACKEND_DIR}}"
    deps: [setup-backend]
    cmds:
      - echo "Initializing database..."
      - "../{{.VENV_DIR}}/bin/python -c 'from app.db.database import db_manager; db_manager.init_db()'"

  # Utility tasks
  clean:
    desc: Clean up generated files and caches
    cmds:
      - task: stop-bg
      - rm -rf {{.VENV_DIR}}
      - rm -rf {{.BACKEND_DIR}}/__pycache__
      - rm -rf {{.BACKEND_DIR}}/app/__pycache__
      - find {{.BACKEND_DIR}} -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find {{.BACKEND_DIR}} -type f -name "*.pyc" -delete
      - rm -rf {{.FRONTEND_DIR}}/node_modules
      - rm -rf {{.FRONTEND_DIR}}/dist
      - rm -rf .pids
      - echo "Cleaned up build artifacts and dependencies"

  clean-db:
    desc: Remove all database files (WARNING - deletes all data)
    cmds:
      - echo "WARNING - This will delete all database files"
      - rm -f {{.BACKEND_DIR}}/data/*.db
      - echo "Database files removed"

  test-backend:
    desc: Run backend tests
    dir: "{{.BACKEND_DIR}}"
    deps: [setup-backend]
    cmds:
      - "../{{.VENV_DIR}}/bin/pytest"

  lint-backend:
    desc: Run backend linter
    dir: "{{.BACKEND_DIR}}"
    deps: [setup-backend]
    cmds:
      - "../{{.VENV_DIR}}/bin/ruff check ."

  format-backend:
    desc: Format backend code
    dir: "{{.BACKEND_DIR}}"
    deps: [setup-backend]
    cmds:
      - "../{{.VENV_DIR}}/bin/ruff format ."

  # Health check tasks
  health:
    desc: Check if backend is running
    cmds:
      - curl -s http://localhost:{{.BACKEND_PORT}}/health | python3 -m json.tool || echo "Backend not running"

  # Install github-copilot-cli
  install-copilot-cli:
    desc: Install GitHub Copilot CLI (requires npm)
    cmds:
      - npm install -g @githubnext/github-copilot-cli
      - echo "GitHub Copilot CLI installed. Run github-copilot-cli auth to authenticate"

  # Quick start
  start:
    desc: Quick start - setup and start in background
    cmds:
      - task: setup
      - echo ""
      - echo "=========================================="
      - echo "Starting Change-Driven Development System"
      - echo "=========================================="
      - echo ""
      - task: start-bg
      - echo ""
      - echo "Applications running in background"
      - echo ""
      - echo "Useful commands:"
      - echo "  task status-bg       - Check status"
      - echo "  task logs            - View all logs"
      - echo "  task logs-backend    - View backend logs"
      - echo "  task logs-frontend   - View frontend logs"
      - echo "  task restart-bg      - Restart services"
      - echo "  task stop-bg         - Stop services"
      - echo ""

  # Service management tasks
  service-install:
    desc: Install systemd services (requires sudo)
    cmds:
      - mkdir -p logs
      - mkdir -p /tmp/cdd-services
      - sed -e "s|{{{{PROJECT_DIR}}}}|$(pwd)|g" -e "s|{{{{USER}}}}|$(whoami)|g" systemd/cdd-backend.service > /tmp/cdd-services/cdd-backend.service
      - sed -e "s|{{{{PROJECT_DIR}}}}|$(pwd)|g" -e "s|{{{{USER}}}}|$(whoami)|g" systemd/cdd-frontend.service > /tmp/cdd-services/cdd-frontend.service
      - sudo cp /tmp/cdd-services/*.service /etc/systemd/system/
      - rm -rf /tmp/cdd-services
      - sudo systemctl daemon-reload
      - echo "Services installed. Run task service-enable to enable auto-start"

  service-enable:
    desc: Enable services to start on boot (requires sudo)
    cmds:
      - sudo systemctl enable cdd-backend
      - sudo systemctl enable cdd-frontend
      - echo "Services enabled for auto-start"

  service-start:
    desc: Start all services (requires sudo)
    cmds:
      - sudo systemctl start cdd-backend
      - sudo systemctl start cdd-frontend
      - sleep 2
      - task: service-status

  service-stop:
    desc: Stop all services (requires sudo)
    cmds:
      - sudo systemctl stop cdd-backend
      - sudo systemctl stop cdd-frontend

  service-restart:
    desc: Restart all services (requires sudo)
    cmds:
      - sudo systemctl restart cdd-backend
      - sudo systemctl restart cdd-frontend
      - sleep 2
      - task: service-status

  service-status:
    desc: Show status of all services
    cmds:
      - sudo systemctl status cdd-backend --no-pager || true
      - echo ""
      - sudo systemctl status cdd-frontend --no-pager || true

  service-logs:
    desc: Tail service logs (Ctrl+C to exit)
    cmds:
      - sudo journalctl -u cdd-backend -u cdd-frontend -f

  service-uninstall:
    desc: Uninstall systemd services (requires sudo)
    cmds:
      - sudo systemctl stop cdd-backend cdd-frontend || true
      - sudo systemctl disable cdd-backend cdd-frontend || true
      - sudo rm -f /etc/systemd/system/cdd-backend.service
      - sudo rm -f /etc/systemd/system/cdd-frontend.service
      - sudo systemctl daemon-reload
      - echo "Services uninstalled"


